language: python
python:
  - "3.5"

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gfortran

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install .

script: pytest
